before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  - SECRET_KEY_BASE=f882ca5935ec798da10449b7714328cc62cd17e643224d0d9cda12b11d30c0b74d955e7237fbec5e14f33eca58fa0401cf2f6134d8cc4512641938098304c6c8
install:
  - bin/setup
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  email: false
rvm:
  - 2.3.0
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 053245fabbb2741c74ee6f349fcc5d48d4e92d2dce810470cd0cf09c1f6a18f0
sudo: false
